# Generated by Django 2.2.5 on 2019-09-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_str', models.CharField(max_length=50)),
                ('obj_buid', models.IntegerField()),
                ('obj_par', models.IntegerField()),
                ('obj_number', models.IntegerField()),
                ('manage_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ManageComp')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_date', models.DateTimeField(verbose_name='date published')),
                ('ticket_user', models.IntegerField()),
                ('ticket_content', models.CharField(max_length=1000)),
                ('ticket_state', models.CharField(max_length=15)),
                ('ticket_duration', models.DurationField()),
                ('ticket_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Object')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TicketType')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(verbose_name='date published')),
                ('comment_content', models.CharField(max_length=500)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Ticket')),
            ],
        ),
    ]
