# Generated by Django 2.2.5 on 2019-09-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190918_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.TicketStatus'),
        ),
    ]
