# Generated by Django 2.2.5 on 2019-09-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190920_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objbuild',
            old_name='buid',
            new_name='build',
        ),
    ]
