# Generated by Django 2.2.5 on 2019-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190920_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
