# Generated by Django 2.2.5 on 2019-09-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_comments_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='obj_aperture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_build_housing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_carrying',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_communication',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_exp_start',
            field=models.DateTimeField(null=True, verbose_name='start exploitation date'),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_factory_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_inspection',
            field=models.DateTimeField(null=True, verbose_name='last inspection date'),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_manufacture',
            field=models.DateTimeField(null=True, verbose_name='object manufacture date'),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_manufacturer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_build',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_par',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='obj_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ObjArea'),
        ),
    ]
