# Generated by Django 2.2.5 on 2019-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190924_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managecomp',
            name='comp_name',
            field=models.CharField(max_length=100),
        ),
    ]
