# Generated by Django 2.2.5 on 2019-09-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190927_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_duration',
            field=models.DurationField(null=True, verbose_name='Время простоя'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TicketType', verbose_name='Тип заявки'),
        ),
    ]
