# Generated by Django 2.2.5 on 2019-09-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20190927_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_build',
            field=models.CharField(default='-', max_length=15, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_build_housing',
            field=models.CharField(max_length=2, null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_par',
            field=models.IntegerField(default=1, verbose_name='Парадная'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_str',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.ObjStr', verbose_name='Улица'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_build',
            field=models.CharField(max_length=15, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_build_housing',
            field=models.CharField(max_length=2, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Номер лифта'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Object', verbose_name='Объект заявки'),
        ),
    ]
