# Generated by Django 2.2.5 on 2019-10-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_ticket_ticket_obj_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='obj_in_service',
            field=models.BooleanField(default=1, verbose_name='Находится на обслуживании'),
            preserve_default=False,
        ),
    ]
