# Generated by Django 2.2.5 on 2019-10-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20191014_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='objstr',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ObjArea', verbose_name='Район'),
        ),
    ]
