# Generated by Django 2.2.5 on 2019-10-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_objstr_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='obj_build_housing',
            field=models.CharField(max_length=5, null=True, verbose_name='Корпус'),
        ),
    ]
