# Generated by Django 2.2.5 on 2019-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20191021_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='obj_build_housing',
            field=models.CharField(max_length=10, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_build_housing',
            field=models.CharField(max_length=10, null=True, verbose_name='Корпус'),
        ),
    ]
