# Generated by Django 2.2.5 on 2019-10-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20191021_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='manage_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ManageComp', verbose_name='Управляющая компания'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_aperture',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_build_housing',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_carrying',
            field=models.IntegerField(blank=True, null=True, verbose_name='Грузоподъемность'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_exp_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала эксплуатации'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_inspection',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней инспекции'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_manufacture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ObjManufacturer', verbose_name='Завод производитель'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер лифта'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_par',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер парадной'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ObjType', verbose_name='Тип объекта'),
        ),
    ]
