# Generated by Django 2.2.5 on 2019-10-30 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20191030_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objmanufacturer',
            options={'verbose_name': 'Завод производитель', 'verbose_name_plural': 'Заводы производители'},
        ),
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Тип заявки', 'verbose_name_plural': 'Типы заявок'},
        ),
        migrations.AlterField(
            model_name='object',
            name='manage_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.ManageComp', verbose_name='Управляющая компания'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.ObjArea', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.ObjManufacturer', verbose_name='Завод производитель'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_str',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ObjStr', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.ObjType', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_obj_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.ObjType', verbose_name='Тип лифта'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='base.TicketStatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_str',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ObjStr', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.TicketType', verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
