# Generated by Django 2.2.6 on 2019-10-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20191030_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUR_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа причин заявок',
                'verbose_name_plural': '09. Группы причин заявок',
            },
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': '07. Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='managecomp',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': '02. Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Лифт', 'verbose_name_plural': '01. Лифты'},
        ),
        migrations.AlterModelOptions(
            name='objmanufacturer',
            options={'verbose_name': 'Завод производитель', 'verbose_name_plural': '02. Заводы производители'},
        ),
        migrations.AlterModelOptions(
            name='objstr',
            options={'verbose_name': 'Улица', 'verbose_name_plural': '02. Улицы'},
        ),
        migrations.AlterModelOptions(
            name='objtype',
            options={'verbose_name': 'Тип лифта', 'verbose_name_plural': '02. Типы лифтов'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': '07. Заявки'},
        ),
        migrations.CreateModel(
            name='FUReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField(max_length=2000, verbose_name='Содержание')),
                ('reason_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.FUR_group', verbose_name='Группа списка причин')),
            ],
            options={
                'verbose_name': 'Часто используемая причина',
                'verbose_name_plural': '09. Часто используемые причины',
            },
        ),
    ]
