# Generated by Django 2.2.5 on 2019-11-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_fur_group_fureason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': '07. Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='fur_group',
            options={'verbose_name': 'Группа причин заявок', 'verbose_name_plural': '09. Группы причин заявок'},
        ),
        migrations.AlterModelOptions(
            name='fureason',
            options={'verbose_name': 'Часто используемая причина', 'verbose_name_plural': '09. Часто используемые причины'},
        ),
        migrations.AlterModelOptions(
            name='managecomp',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': '02. Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='objarea',
            options={'verbose_name': 'Район', 'verbose_name_plural': '02. Районы'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Лифт', 'verbose_name_plural': '01. Лифты'},
        ),
        migrations.AlterModelOptions(
            name='objmanufacturer',
            options={'verbose_name': 'Завод производитель', 'verbose_name_plural': '02. Заводы производители'},
        ),
        migrations.AlterModelOptions(
            name='objstr',
            options={'verbose_name': 'Улица', 'verbose_name_plural': '02. Улицы'},
        ),
        migrations.AlterModelOptions(
            name='objtype',
            options={'verbose_name': 'Тип лифта', 'verbose_name_plural': '02. Типы лифтов'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': '07. Заявки'},
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('optional_name', models.CharField(max_length=15, verbose_name='Отчество')),
                ('worker_recruitment', models.DateTimeField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('worker_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ObjArea', verbose_name='Район сотрудника')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Worker'),
        ),
    ]
