# Generated by Django 2.2.5 on 2019-11-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20191113_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': '08. Работники'},
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Дополнительный телефон'),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_work',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Рабочий телефон'),
        ),
    ]
