# Generated by Django 2.2.5 on 2019-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20191118_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_recruitment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
    ]
