# Generated by Django 2.2.5 on 2019-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20191126_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'verbose_name': 'Тип заявки', 'verbose_name_plural': '07. Типы заявок'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_sender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Заявитель'),
        ),
    ]
