# Generated by Django 2.2.5 on 2019-12-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20191204_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='obj_par_alter',
            field=models.BooleanField(default=False, null=True, verbose_name='Литеральный номер парадной'),
        ),
    ]
