# Generated by Django 2.2.5 on 2020-06-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_object_obj_par_alter'),
    ]

    operations = [
        migrations.AddField(
            model_name='managecomp',
            name='decline_period',
            field=models.DurationField(blank=True, null=True, verbose_name='Период простоя до акта снижения'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obj_par_alter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Литеральный номер парадной'),
        ),
    ]
