# Generated by Django 2.2.5 on 2020-08-08 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20200617_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='managecomp',
            name='decline_period',
            field=models.DurationField(blank=True, default=datetime.timedelta(1), null=True, verbose_name='Период простоя до акта снижения'),
        ),
    ]
