# Generated by Django 2.2.5 on 2020-08-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20200809_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_build_housing',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Время простоя'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_obj_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.ObjType', verbose_name='Тип лифта'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_par',
            field=models.IntegerField(blank=True, null=True, verbose_name='Парадная'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.TicketType', verbose_name='Тип заявки'),
        ),
    ]
